name: verify

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip3 install -U online-judge-verify-helper

    - name: Run tests (Generate Docs)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
      run: oj-verify all

    - name: Fix Documentation Config
      run: |
        cd .verify-helper/markdown
        rm -f .nojekyll
        
        echo "title: CP-Library" > _config.yml
        echo "theme: jekyll-theme-minimal" >> _config.yml
        echo "enable_mathjax: true" >> _config.yml
        
        echo "plugins:" >> _config.yml
        echo "  - jemoji" >> _config.yml
        
        echo "description: Competitive Programming Library" >> _config.yml
        echo "url: 'https://joji0.github.io'" >> _config.yml
        echo "baseurl: '/CP-Library'" >> _config.yml
        
        if [ ! -f index.md ]; then
          echo "Copying README to index.md..."
          cp ../../README.md index.md
        fi

    - name: Deploy to GitHub Pages
      if: success() && github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .verify-helper/markdown
        keep_files: false
        force_orphan: true
        enable_jekyll: true  
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
